### ISSUE TITLE
Improve Suggestion: Non-JSON objects may be passed through the stream

### ISSUE THREAD

**Issue by myConsciousness** [myConsciousness/atproto.dart#487]
# 1. What could be improved

Just ignore this object.

# 2. Why should this be improved

# 3. Any risks?

# 4. More information

**Comment by myConsciousness** [comment]
```bash
Unhandled exception:
type 'List<Object?>' is not a subtype of type 'Map<String, dynamic>'
#0      convertSubscribeRepoUpdates (package:atproto/src/converter/subscribe_repo_updates_converter.dart:12:12)
#1      _convertData (package:xrpc/src/xrpc.dart:571:35)
#2      subscribe.<anonymous closure> (package:xrpc/src/xrpc.dart:368:18)
#3      _RootZone.runUnaryGuarded (dart:async/zone.dart:1594:10)
#4      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#5      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#6      _ForwardingStreamSubscription._add (dart:async/stream_pipe.dart:123:11)
#7      _HandleErrorStream._handleData (dart:async/stream_pipe.dart:253:10)
#8      _ForwardingStreamSubscription._handleData (dart:async/stream_pipe.dart:153:13)
#9      _RootZone.runUnaryGuarded (dart:async/zone.dart:1594:10)
#10     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#11     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
```
